# Generated by Django 4.1.3 on 2022-12-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='displayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('police_station', models.CharField(max_length=50)),
                ('how_come', models.CharField(max_length=50)),
                ('time_taken', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('feedback', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
