# Generated by Django 4.1.3 on 2022-12-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseReport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stateWisePoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=15)),
                ('police_station', models.CharField(max_length=15)),
            ],
        ),
    ]
