# Generated by Django 4.1.3 on 2022-12-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databaseReport", "0002_statewisepolicestation"),
    ]

    operations = [
        migrations.AddField(
            model_name="statewisepolicestation",
            name="qr_code",
            field=models.FileField(
                default=None, max_length=250, null=True, upload_to="qrCodes/"
            ),
        ),
    ]
